AWSTemplateFormatVersion: 2010-09-09
Description: KeyName Parameter demo

Parameters:
  MyKeyName:
    Description: Enter My KeyName
    Type: AWS::EC2::KeyPair::KeyName
    Default: cfn-key-1
    AllowedValues:
      - cfn-key-1
      - cfn-key-2
  MyAvailabilityZone:
    Description: Select Availability Zone
    Type: String
    Default: us-east-2a
    AllowedValues:
      - us-east-2a
      - us-east-2b
      - us-east-2c

Resources:
  DevEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0cd3dfa4e37921605
      InstanceType: t2.micro
      KeyName: !Ref MyKeyName
      SecurityGroups:
        - default
        - !Ref SSHSecurityGroup
      AvailabilityZone: !Ref MyAvailabilityZone
  SSHSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: my new SSH security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
